using Microsoft.EntityFrameworkCore;

namespace Budget.Api.Data;

/// <summary>
/// EnsureCreated only builds a database from scratch; it never adds tables to one that
/// already exists. Until the project moves to EF migrations, tables added after the first
/// deploy are created here, idempotently, so a live database picks them up on next start.
/// </summary>
public static class SchemaUpgrade
{
    public static async Task ApplyAsync(BudgetDbContext db)
    {
        if (db.Database.IsSqlServer())
            await db.Database.ExecuteSqlRawAsync(SqlServerRecurring);
        else if (db.Database.IsSqlite())
            foreach (var sql in SqliteRecurring)
                await db.Database.ExecuteSqlRawAsync(sql);
    }

    // DDL as generated by EF for the RecurringItem mapping in BudgetDbContext.
    private const string SqlServerRecurring = """
        IF OBJECT_ID(N'[RecurringItems]', N'U') IS NULL
        BEGIN
            CREATE TABLE [RecurringItems] (
                [Id] int NOT NULL IDENTITY,
                [Name] nvarchar(200) NOT NULL,
                [Amount] decimal(18,2) NOT NULL,
                [CategoryId] int NOT NULL,
                [Frequency] int NOT NULL,
                [Interval] int NOT NULL,
                [StartDate] date NOT NULL,
                [EndDate] date NULL,
                [NextDueDate] date NOT NULL,
                [LastPostedDate] date NULL,
                [IsActive] bit NOT NULL,
                [Notes] nvarchar(max) NULL,
                CONSTRAINT [PK_RecurringItems] PRIMARY KEY ([Id]),
                CONSTRAINT [FK_RecurringItems_Categories_CategoryId] FOREIGN KEY ([CategoryId]) REFERENCES [Categories] ([Id]) ON DELETE CASCADE
            );
            CREATE INDEX [IX_RecurringItems_CategoryId] ON [RecurringItems] ([CategoryId]);
            CREATE INDEX [IX_RecurringItems_NextDueDate] ON [RecurringItems] ([NextDueDate]);
        END
        """;

    private static readonly string[] SqliteRecurring =
    [
        """
        CREATE TABLE IF NOT EXISTS "RecurringItems" (
            "Id" INTEGER NOT NULL CONSTRAINT "PK_RecurringItems" PRIMARY KEY AUTOINCREMENT,
            "Name" TEXT NOT NULL,
            "Amount" TEXT NOT NULL,
            "CategoryId" INTEGER NOT NULL,
            "Frequency" INTEGER NOT NULL,
            "Interval" INTEGER NOT NULL,
            "StartDate" TEXT NOT NULL,
            "EndDate" TEXT NULL,
            "NextDueDate" TEXT NOT NULL,
            "LastPostedDate" TEXT NULL,
            "IsActive" INTEGER NOT NULL,
            "Notes" TEXT NULL,
            CONSTRAINT "FK_RecurringItems_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE CASCADE
        );
        """,
        """CREATE INDEX IF NOT EXISTS "IX_RecurringItems_CategoryId" ON "RecurringItems" ("CategoryId");""",
        """CREATE INDEX IF NOT EXISTS "IX_RecurringItems_NextDueDate" ON "RecurringItems" ("NextDueDate");"""
    ];
}
